export { optionsMiddleware as automation, protectAutomationCredentials } from './automation';
export { makeMiddleware as dependencies, ensureDependencies, preventSelfDependency } from './dependencies';
export { featureMiddleware as eslint } from './eslint';
export { makeMiddleware as forceOptions } from './force-options';
export { makeMiddleware as defaultOptions } from './default-options';
export { featureMiddleware as logo } from './logo';
export { featureMiddleware as nodeVersion } from './node-version';
export { makeMiddleware as packageInfo } from './package-info';
export { optionsMiddleware as release } from './release';
export { trustedPublisherFix as trustedPublisherFix } from './release';
export { featureMiddleware as selfMutationOnForks } from './self-mutation';
